- name : play level variables
  hosts : local
  connection : local
  vars:
    COURSE : DevOps With Aws
    DURATION : 10HRS
    Trainer : Sivakumar reddy
  
  tasks :
    - name : print the course info
      vars :
        COURSE : Ansible
      ansible.builtin.debug:
        msg : "Course Name is : {{ COURSE }}, Duration : {{ DURATION}}, Trainer : {{ Trainer}}"